/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
using https://gltf.pmnd.rs
*/

import { useMemo, forwardRef } from "react";
import { useGLTF } from "@react-three/drei";
import { Vector3 } from "three";
import { GhibliShader } from "./shader";

export const Trees = forwardRef((props, ref) => {
  const { nodes } = useGLTF("/trees.glb");

  const uniforms = useMemo(
    () => ({
      colorMap: {
        value: props.colors,
      },
      brightnessThresholds: {
        value: [0.6, 0.35, 0.001],
      },
      lightPosition: { value: new Vector3(15, 15, 15) },
    }),
    [props.colors]
  );

  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Foliage.geometry}
        position={[0.327, -0.046, -0.684]}
      >
        {/* <meshStandardMaterial
          color={new Color("#33584e").convertLinearToSRGB()}
        /> */}
        <shaderMaterial
          attach="material"
          {...GhibliShader}
          uniforms={uniforms}
        />
      </mesh>
    </group>
  );
});

Trees.displayName = "Trees";

useGLTF.preload("/trees.glb");
